#ifndef CDX_BASE_ERRNO_H
#define CDX_BASE_ERRNO_H

#define CDX_ERRNO_BASE 0x04670000
#define CDX_ERRNO_PART_SIZE 0x1000

/**
 *CDX_ERR_RTSP_EDGE = CDX_ERRNO_BASE + CDX_ERRNO_PART_SIZE,
 */

//#define CDX_ERRNO_BASE CDX_ERRNO_BASE + 1024

enum CdxBaseErrno
{
    CDX_ERR_BASE_EDGE = CDX_ERRNO_BASE,
    CDX_ERR_BASE_MEMORY,
    
    CDX_ERR_BASE_BUF_OVER_READ,

    CDX_ERR_BASE_MSG_ROSTER_NORUNNING,
    CDX_ERR_BASE_MSG_ITEM_NOTFOUND,
    CDX_ERR_BASE_CREATE_MSG_FAIL,

    CDX_ERR_BASE_META_ITEM_NOTFOUND,

    CDX_ERR_QUEUE_NOTREADY,
};

#endif
